-- 0001_init.sql
-- BTE platform. Authoritative source: docs/DATA_MODEL.md
--
-- Agents: do not edit this file. Schema changes are a new migration, by the
-- foundation owner. Do not weaken a constraint to make a write succeed.
--
-- Every CHECK and unique index below exists because a governing document says
-- so. Enforcing them here means six features cannot each interpret them
-- slightly differently.

create extension if not exists "pgcrypto";

-- ============================================================
-- Enums
-- ============================================================
create type person_status as enum ('pending', 'verified', 'hidden', 'inactive');
create type department_kind as enum ('team', 'campus_chapter');
create type membership_role as enum (
  'founder', 'coordinator', 'campus_lead', 'assistant_lead', 'practitioner', 'member'
);
create type badge_kind as enum ('called', 'filled', 'skilled');
create type application_status as enum (
  'draft', 'submitted', 'under_review', 'interview',
  'offered', 'conditional', 'declined', 'withdrawn', 'lapsed'
);
create type reliability_result as enum ('pass', 'concern', 'fail');
create type approach_outcome as enum ('live', 'declined', 'accepted', 'lapsed');
create type chapter_status as enum ('approved', 'active', 'at_risk', 'dormant', 'closed');
create type meeting_format as enum ('ninety', 'sixty');
create type meeting_status as enum ('scheduled', 'held', 'cancelled');
create type shift_delivery as enum ('full', 'shortened', 'missed');
create type member_status as enum ('member', 'observer');
create type build_log_kind as enum ('shipped', 'learned', 'stuck');
create type submission_status as enum ('submitted', 'in_review', 'reviewed', 'expo_offered');
create type escalation_category as enum (
  'money', 'press', 'fellowship', 'safety', 'name_use', 'signature', 'chapter_slipping'
);

-- ============================================================
-- Platform core
-- ============================================================
create table people (
  id              uuid primary key default gen_random_uuid(),
  auth_user_id    uuid unique,
  full_name       text not null,
  email           text not null unique,
  phone           text,
  status          person_status not null default 'pending',
  graduation_year int,
  year_group      int,
  created_at      timestamptz not null default now(),
  verified_at     timestamptz
);

create table departments (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  kind        department_kind not null,
  parent_id   uuid references departments(id),
  created_at  timestamptz not null default now(),
  archived_at timestamptz
);

create table memberships (
  id            uuid primary key default gen_random_uuid(),
  person_id     uuid not null references people(id) on delete cascade,
  department_id uuid not null references departments(id) on delete cascade,
  role          membership_role not null,
  started_at    date not null default current_date,
  ended_at      date,
  constraint membership_dates check (ended_at is null or ended_at >= started_at)
);

create unique index memberships_one_live_role
  on memberships (person_id, department_id, role)
  where ended_at is null;

create table badges (
  id         uuid primary key default gen_random_uuid(),
  person_id  uuid not null references people(id) on delete cascade,
  badge      badge_kind not null,
  awarded_at date not null default current_date,
  unique (person_id, badge)
);

-- ============================================================
-- Campus module
-- ============================================================
create table institutions (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  city       text,
  created_at timestamptz not null default now()
);

create table cohorts (
  id                    uuid primary key default gen_random_uuid(),
  name                  text not null,
  academic_year         text not null,
  applications_open_at  date,
  applications_close_at date,
  interviews_from       date,
  interviews_to         date,
  outcomes_at           date,
  onboarding_call_at    timestamptz,
  chapters_cap          int not null default 3,
  status                text not null default 'planned',
  created_at            timestamptz not null default now(),
  constraint cohort_window check (
    applications_close_at is null
    or applications_open_at is null
    or applications_close_at >= applications_open_at
  ),
  constraint cohort_cap_sane check (chapters_cap between 1 and 20)
);

create table fellowships (
  id             uuid primary key default gen_random_uuid(),
  institution_id uuid not null references institutions(id),
  name           text not null,
  leader_name    text,
  leader_role    text,
  contact_phone  text,
  contact_email  text,
  created_at     timestamptz not null default now(),
  unique (institution_id, name)
);

-- Peer risk. One live approach per institution, enforced at write time rather
-- than by a coordinator remembering. Charter 11.3.
create table fellowship_approaches (
  id               uuid primary key default gen_random_uuid(),
  fellowship_id    uuid not null references fellowships(id),
  institution_id   uuid not null references institutions(id),
  opened_by        uuid not null references people(id),
  opened_at        date not null default current_date,
  window_closes_at date not null,
  outcome          approach_outcome not null default 'live',
  closed_at        date,
  constraint approach_window check (window_closes_at > opened_at)
);

create unique index fellowship_one_live_approach_per_institution
  on fellowship_approaches (institution_id)
  where outcome = 'live';

create table applications (
  id                   uuid primary key default gen_random_uuid(),
  cohort_id            uuid not null references cohorts(id),
  institution_id       uuid not null references institutions(id),
  lead_person_id       uuid not null references people(id),
  assistant_person_id  uuid references people(id),
  track_record         text,
  video_url            text,
  answer_problem       text,
  answer_faith_method  text,
  answer_failure       text,
  availability_note    text,
  status               application_status not null default 'draft',
  submitted_at         timestamptz,
  conditional_deadline date,
  created_at           timestamptz not null default now(),
  -- Charter 6. Eligibility is a hard gate, not a scoring dimension.
  constraint pair_is_two_people check (
    assistant_person_id is null or assistant_person_id <> lead_person_id
  ),
  constraint conditional_needs_deadline check (
    status <> 'conditional' or conditional_deadline is not null
  ),
  constraint submitted_needs_timestamp check (
    status = 'draft' or submitted_at is not null
  )
);

create unique index applications_one_live_per_pair
  on applications (cohort_id, institution_id, lead_person_id)
  where status not in ('withdrawn', 'declined', 'lapsed');

create table application_scores (
  id                  uuid primary key default gen_random_uuid(),
  application_id      uuid not null references applications(id) on delete cascade,
  reviewer_id         uuid not null references people(id),
  score_groundwork    int not null,
  score_track_record  int not null,
  score_written       int not null,
  score_video         int not null,
  score_pair          int not null,
  score_availability  int not null,
  score_technical     int not null,
  weighted_total      int generated always as (
      score_groundwork   * 3
    + score_track_record * 2
    + score_written      * 2
    + score_video        * 2
    + score_pair         * 2
    + score_availability * 1
    + score_technical    * 1
  ) stored,
  red_flags  text,
  decision   text,
  scored_at  timestamptz not null default now(),
  unique (application_id, reviewer_id),
  constraint scores_in_range check (
    score_groundwork   between 0 and 3 and
    score_track_record between 0 and 3 and
    score_written      between 0 and 3 and
    score_video        between 0 and 3 and
    score_pair         between 0 and 3 and
    score_availability between 0 and 3 and
    score_technical    between 0 and 3
  )
);

create table fellowship_scorecards (
  id                    uuid primary key default gen_random_uuid(),
  application_id        uuid not null references applications(id) on delete cascade,
  fellowship_id         uuid not null references fellowships(id),
  -- Section A. The reliability test is a gate, not a score.
  ask_description       text,
  asked_on              date,
  replied_on            date,
  did_reply             boolean,
  did_show              boolean,
  was_done              boolean,
  delegation            text,
  reliability_result    reliability_result,
  -- Section B. Ranked criteria, size last.
  score_media_unit      int,
  score_venue           int,
  score_open_meeting    int,
  score_size            int,
  evidence_media_unit   text,
  evidence_venue        text,
  evidence_open_meeting text,
  evidence_size         text,
  -- Section C
  venue_permanent       boolean,
  venue_power           boolean,
  venue_capacity        int,
  venue_safe_access     boolean,
  venue_seen            boolean,
  proposed_day_time     text,
  -- Section D. Attending is fine. Not disclosing is not.
  applicant_attends     boolean,
  applicant_role        text,
  close_relation_leads  boolean,
  recommendation        text,
  submitted_at          timestamptz,
  unique (application_id),
  constraint scorecard_scores_in_range check (
    coalesce(score_media_unit, 0)   between 0 and 3 and
    coalesce(score_venue, 0)        between 0 and 3 and
    coalesce(score_open_meeting, 0) between 0 and 3 and
    coalesce(score_size, 0)         between 0 and 3
  )
);

create table interviews (
  id                      uuid primary key default gen_random_uuid(),
  application_id          uuid not null references applications(id) on delete cascade,
  interviewer_id          uuid not null references people(id),
  held_at                 timestamptz,
  score_groundwork_holds  int,
  score_assistant_real    int,
  score_holds_room        int,
  score_escalates         int,
  score_works_in_system   int,
  score_honest            int,
  total int generated always as (
      coalesce(score_groundwork_holds, 0)
    + coalesce(score_assistant_real, 0)
    + coalesce(score_holds_room, 0)
    + coalesce(score_escalates, 0)
    + coalesce(score_works_in_system, 0)
    + coalesce(score_honest, 0)
  ) stored,
  concern_note   text,
  recommendation text,
  scored_at      timestamptz
);

-- A chapter IS a department. campus_chapters extends it.
create table campus_chapters (
  id                  uuid primary key default gen_random_uuid(),
  department_id       uuid not null unique references departments(id),
  institution_id      uuid not null references institutions(id),
  fellowship_id       uuid references fellowships(id),
  cohort_id           uuid references cohorts(id),
  lead_person_id      uuid references people(id),
  assistant_person_id uuid references people(id),
  status              chapter_status not null default 'approved',
  launched_at         date,
  closed_at           date,
  created_at          timestamptz not null default now(),
  constraint chapter_pair_is_two_people check (
    assistant_person_id is null or assistant_person_id <> lead_person_id
  )
);

create unique index chapters_one_active_per_institution
  on campus_chapters (institution_id)
  where status in ('approved', 'active', 'at_risk');

create table chapter_approvals (
  id         uuid primary key default gen_random_uuid(),
  chapter_id uuid not null unique references campus_chapters(id) on delete cascade,
  gate1_people      boolean not null default false,
  gate2_selection   boolean not null default false,
  gate3_fellowship  boolean not null default false,
  gate4_venue       boolean not null default false,
  gate5_commitment  boolean not null default false,
  gate6_onboarding  boolean not null default false,
  gate8_letter      boolean not null default false,
  gate7_systems     boolean not null default false,
  gate1_confirmed_at timestamptz, gate1_confirmed_by uuid references people(id),
  gate2_confirmed_at timestamptz, gate2_confirmed_by uuid references people(id),
  gate3_confirmed_at timestamptz, gate3_confirmed_by uuid references people(id),
  gate4_confirmed_at timestamptz, gate4_confirmed_by uuid references people(id),
  gate5_confirmed_at timestamptz, gate5_confirmed_by uuid references people(id),
  gate6_confirmed_at timestamptz, gate6_confirmed_by uuid references people(id),
  gate7_confirmed_at timestamptz, gate7_confirmed_by uuid references people(id),
  gate8_confirmed_at timestamptz, gate8_confirmed_by uuid references people(id),
  gate1_evidence text, gate2_evidence text, gate3_evidence text, gate4_evidence text,
  gate5_evidence text, gate6_evidence text, gate7_evidence text, gate8_evidence text,
  conditional          boolean not null default false,
  conditional_deadline date,
  outcome              text,
  decided_at           timestamptz,
  coordinator_id       uuid references people(id),
  countersigned_by     uuid references people(id),
  all_gates_clear boolean generated always as (
    gate1_people and gate2_selection and gate3_fellowship and gate4_venue
    and gate5_commitment and gate6_onboarding and gate7_systems and gate8_letter
  ) stored
);

create table open_meeting_confirmations (
  id                    uuid primary key default gen_random_uuid(),
  chapter_id            uuid not null references campus_chapters(id) on delete cascade,
  fellowship_id         uuid not null references fellowships(id),
  host_signatory_name   text not null,
  host_signatory_role   text,
  signed_at             date not null,
  academic_year         text not null,
  document_url          text,
  unique (chapter_id, academic_year)
);

create table terms (
  id                 uuid primary key default gen_random_uuid(),
  chapter_id         uuid not null references campus_chapters(id) on delete cascade,
  academic_year      text not null,
  term_number        int not null,
  dates_published_at timestamptz,
  unique (chapter_id, academic_year, term_number),
  constraint term_number_valid check (term_number in (1, 2))
);

create table meetings (
  id             uuid primary key default gen_random_uuid(),
  chapter_id     uuid not null references campus_chapters(id) on delete cascade,
  term_id        uuid not null references terms(id) on delete cascade,
  meeting_number int not null,
  scheduled_for  timestamptz not null,
  format         meeting_format not null default 'ninety',
  status         meeting_status not null default 'scheduled',
  unique (term_id, meeting_number),
  constraint meeting_number_valid check (meeting_number between 1 and 4)
);

create table meeting_reports (
  id                    uuid primary key default gen_random_uuid(),
  meeting_id            uuid not null unique references meetings(id) on delete cascade,
  filed_by              uuid not null references people(id),
  filed_at              timestamptz not null default now(),
  -- The five fields. All required. Run Sheet and Report Form.
  attendance_total      int not null,
  first_timers          int not null default 0,
  practitioner_block    text not null,
  practitioner_person_id uuid references people(id),
  demonstrators         text not null,
  blocked               text not null,
  submissions_noted     text not null,
  -- The Shift never gets cut. If it was, we want the reason, not silence.
  shift_ran             shift_delivery not null,
  shift_reason          text,
  shift_feedback        text,
  shift_pack_version    text,
  coordinator_flags     text,
  flags_read_at         timestamptz,
  flags_read_by         uuid references people(id),
  constraint attendance_non_negative check (attendance_total >= 0 and first_timers >= 0),
  constraint first_timers_within_total check (first_timers <= attendance_total),
  constraint shift_shortfall_needs_reason check (
    shift_ran = 'full' or (shift_reason is not null and length(btrim(shift_reason)) > 0)
  )
);

create table chapter_members (
  id                uuid primary key default gen_random_uuid(),
  chapter_id        uuid not null references campus_chapters(id) on delete cascade,
  person_id         uuid not null references people(id) on delete cascade,
  status            member_status not null default 'member',
  joined_at         date not null default current_date,
  status_changed_at timestamptz,
  unique (chapter_id, person_id)
);

create table build_logs (
  id         uuid primary key default gen_random_uuid(),
  chapter_id uuid not null references campus_chapters(id) on delete cascade,
  person_id  uuid not null references people(id) on delete cascade,
  term_id    uuid references terms(id),
  kind       build_log_kind not null,
  body       text not null,
  posted_at  timestamptz not null default now(),
  constraint build_log_has_body check (length(btrim(body)) > 0)
);

create table submissions (
  id           uuid primary key default gen_random_uuid(),
  chapter_id   uuid not null references campus_chapters(id) on delete cascade,
  person_id    uuid not null references people(id) on delete cascade,
  title        text not null,
  description  text not null,
  links        text,
  media_urls   text,
  unfinished   text,
  status       submission_status not null default 'submitted',
  submitted_at timestamptz not null default now()
);

create table reviews (
  id            uuid primary key default gen_random_uuid(),
  submission_id uuid not null unique references submissions(id) on delete cascade,
  reviewer_id   uuid references people(id),
  due_at        timestamptz not null,
  body          text,
  outcome       text,
  returned_at   timestamptz,
  constraint review_returned_has_body check (
    returned_at is null or (body is not null and length(btrim(body)) > 0)
  )
);

create table succession_records (
  id                       uuid primary key default gen_random_uuid(),
  chapter_id               uuid not null references campus_chapters(id) on delete cascade,
  term_id                  uuid references terms(id),
  lead_person_id           uuid references people(id),
  assistant_person_id      uuid references people(id),
  lead_graduation_year     int,
  assistant_graduation_year int,
  assistant_is_real        boolean,
  overlap_started_at       date,
  handover_completed_at    date,
  audited_at               timestamptz,
  audited_by               uuid references people(id),
  notes                    text,
  -- Charter 6. They must not graduate in the same year.
  constraint succession_years_differ check (
    lead_graduation_year is null
    or assistant_graduation_year is null
    or assistant_graduation_year > lead_graduation_year
  )
);

create table escalations (
  id                      uuid primary key default gen_random_uuid(),
  chapter_id              uuid references campus_chapters(id) on delete cascade,
  raised_by               uuid references people(id),
  category                escalation_category not null,
  body                    text not null,
  raised_at               timestamptz not null default now(),
  acknowledged_at         timestamptz,
  resolved_at             timestamptz,
  escalated_to_founder_at timestamptz
);

create table shift_packs (
  id               uuid primary key default gen_random_uuid(),
  term_number      int not null,
  session_number   int not null,
  title            text not null,
  anchor_reference text not null,
  version          text not null,
  published_at     date,
  unique (term_number, session_number, version)
);

-- ============================================================
-- Rules that need more than a CHECK
-- ============================================================

-- Charter 16. Eight gates, then active. Seven green gates still does not launch.
create or replace function enforce_gates_before_active()
returns trigger
language plpgsql
as $$
declare
  gates_clear boolean;
begin
  if new.status in ('active', 'at_risk') then
    select all_gates_clear into gates_clear
    from chapter_approvals where chapter_id = new.id;
    if gates_clear is distinct from true then
      raise exception
        'Chapter cannot become % until all eight approval gates are confirmed', new.status;
    end if;
  end if;
  return new;
end;
$$;

create trigger chapter_gates_before_active
  before insert or update of status on campus_chapters
  for each row execute function enforce_gates_before_active();

-- Scorecard 5.1. A FAIL reliability result cannot back an approval.
create or replace function enforce_fellowship_reliability()
returns trigger
language plpgsql
as $$
declare
  worst reliability_result;
begin
  if new.gate3_fellowship then
    select fs.reliability_result into worst
    from fellowship_scorecards fs
    join applications a on a.id = fs.application_id
    join campus_chapters c on c.institution_id = a.institution_id
    where c.id = new.chapter_id
    order by fs.submitted_at desc nulls last
    limit 1;
    if worst = 'fail' then
      raise exception
        'Gate 3 cannot be confirmed against a scorecard with a FAIL reliability result';
    end if;
  end if;
  return new;
end;
$$;

create trigger approvals_reliability_gate
  before insert or update of gate3_fellowship on chapter_approvals
  for each row execute function enforce_fellowship_reliability();

-- Member Pack. Observers may not submit work.
create or replace function enforce_member_can_submit()
returns trigger
language plpgsql
as $$
declare
  s member_status;
begin
  select status into s
  from chapter_members
  where chapter_id = new.chapter_id and person_id = new.person_id;
  if s is null then
    raise exception 'Only a member of this chapter may submit work';
  end if;
  if s = 'observer' then
    raise exception 'Observers may not submit work. Post a build log to return to member status';
  end if;
  return new;
end;
$$;

create trigger submissions_member_only
  before insert on submissions
  for each row execute function enforce_member_can_submit();

-- Showcase 5.1. The published turnaround window, applied at creation.
create or replace function set_review_due_at()
returns trigger
language plpgsql
as $$
begin
  if new.due_at is null then
    new.due_at := now() + interval '21 days';
  end if;
  return new;
end;
$$;

create trigger reviews_default_window
  before insert on reviews
  for each row execute function set_review_due_at();

-- ============================================================
-- Indexes for the queries the health dashboard actually runs
-- ============================================================
create index meetings_chapter_scheduled  on meetings (chapter_id, scheduled_for desc);
create index reports_filed               on meeting_reports (filed_at desc);
create index reports_unread_flags        on meeting_reports (flags_read_at) where coordinator_flags is not null;
create index build_logs_chapter_posted   on build_logs (chapter_id, posted_at desc);
create index build_logs_person_term      on build_logs (person_id, term_id);
create index submissions_chapter         on submissions (chapter_id, submitted_at desc);
create index reviews_overdue             on reviews (due_at) where returned_at is null;
create index escalations_open            on escalations (raised_at desc) where resolved_at is null;
create index memberships_person          on memberships (person_id) where ended_at is null;
create index applications_cohort_status  on applications (cohort_id, status);
